---

- name: Download HBase
  become: no
  get_url:
    url: "{{ _hbase_url }}"
    dest: "{{ ansible_env.HOME }}/{{ _hbase_url | basename }}"
    checksum: "sha256:{{ _hbase_checksums[hbase_version][hbase_distribution].sha256 }}"
  tags:
    - hbase
    - hbase_install

- name: Extract
  unarchive:
    src: "{{ ansible_env.HOME }}/{{ _hbase_url | basename }}"
    dest: "{{ hbase_prefix }}"
    creates: "{{ hbase_prefix }}/hbase-{{ hbase_version }}"
    copy: no
  tags:
    - hbase
    - hbase_install

- name: Link
  file:
    src: "{{ hbase_prefix }}/hbase-{{ hbase_version }}"
    dest: "{{ hbase_prefix }}/{{ hbase_link_name }}"
    state: link
  tags:
    - hbase
    - hbase_install

- name: Add to /etc/profile.d
  lineinfile:
    dest: /etc/profile.d/hbase.sh
    line: "export {{ item }}"
  with_items:
    - HBASE_HOME={{ hbase_prefix }}/{{ hbase_link_name }}
    - PATH=$PATH:$HBASE_HOME/bin
